### ISSUE TITLE
The link to the paper is not working

### ISSUE THREAD

**Issue by iBrain-007** [zjx1805/ArteryNetwork#1]
Hi, there,

Thank you for contributing quality code to the open-source community. It's a great job!

But the paper link you provided in the ```Readme``` is not working, i.e. 404 error. Would it be convenient for you to provide a new link to the paper?

Regards,
iBrain

**Comment by zjx1805** [comment]
Hi iBrain,

Sure, I have updated the paper info in the README file:

Zhu, J., Teolis, S., Biassou, N., Tabb, A., Jabin, P.E. and Lavi, O., 2020. Tracking the adaptation and compensation processes of patients brain arterial network to an evolving glioblastoma. IEEE transactions on pattern analysis and machine intelligence, p.2020.

Best,
Junxi
